# Generated by Django 5.1 on 2024-09-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_meta_kewords_products_product_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_name',
        ),
    ]
