# Generated by Django 5.1 on 2024-09-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_slug_category_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
